- .gitignore
- build.gradle
- jitpack.yml
https://tools.hmcts.net/jira/browse/RET-915
Added Gradle build and JitPack functionality
```
[ ] Yes
[x ] No
```
> [RET-915-] RET-915-Integrate-Java-Object-Model

- README.md
https://tools.hmcts.net/jira/browse/RET-915
Update README file
```
[ ] Yes
[x] No
```
> [RET-915] Update README file

- build.gradle
- src/main/java/uk/gov/hmcts/ecm/common/model/multiples/MultipleData.java
https://tools.hmcts.net/jira/browse/RET-1189
Merge ECM Release 5.0.25
```
[ ] Yes
[x] No
```
> Merge ECM Release 5.0.25

- .github/workflows/gradle.yml
Add gradle to workflows
```
[ ] Yes
[x] No
```
> Add gradle build to workflows

- build.gradle
- src/main/java/uk/gov/hmcts/ecm/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-1507
Merge ECM Release 5.0.28
```
[ ] Yes
[x] No
```
> Merge ECM Release 5.0.28

- build.gradle
- src/main/java/uk/gov/hmcts/ecm/common/model/ccd/CaseData.java
Fix json for correspondenceScotType
```
[ ] Yes
[x] No
```
> Fix json for correspondenceScotType

- build.gradle
- src/main/java/uk/gov/hmcts/ecm/common/model/ccd/types/JurCodesType.java
> Add missing juridictionCodesSubList1

- build.gradle
- src/main/java/uk/gov/hmcts/ecm/common/model/ccd/types/ClaimantIndType.java
https://tools.hmcts.net/jira/browse/RET-1463
Update ClaimantIndType model to include sex and gender identity properties
```
[ ] Yes
[x] No
```
> [RET-1463] Update CCD config: Sex and Gender identity

- src/main/java/uk/gov/hmcts/et/common/model/ccd/Et1CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/NewEmploymentType.java
https://tools.hmcts.net/jira/browse/RET-1442
```
[ ] Yes
[x] No
```
> add  NewEmploymentDetails

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/Et1CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantRequestType.java
https://tools.hmcts.net/jira/browse/RET-1470
Adding new claimant request type
```
[ ] Yes
[x ] No
```
> Add Claimant Request Type

- src/main/java/uk/gov/hmcts/et/common/model/ccd/Et1CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantHearingPreference.java
https://tools.hmcts.net/jira/browse/RET-1471
Added Claimant Hearing Preference.
```
[ ] Yes
[X] No
```
> Add hearing preference - RET-1471

- build.gradle
Bump version to 1.0.4
```
[ ] Yes
[x] No
```
> Bump version to 1.0.4

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/CorrespondenceScotType.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/CorrespondenceType.java
https://tools.hmcts.net/jira/browse/RET-1793
Merge ECM Releases R5.0.29 / R5.0.30
```
[ ] Yes
[x] No
```
> Merge ECM R5.0.29/30

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/AdditionalCaseInfoType.java
https://tools.hmcts.net/jira/browse/RET-1983
Merge ECM R5.0.31
```
[ ] Yes
[x] No
```
> Merge ECM R5.0.31

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/Et1CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantHearingPreference.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantOtherType.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantRequestType.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantType.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/TaskListCheckType.java
https://tools.hmcts.net/jira/browse/RET-2013
Adding missing data fields
```
[ ] Yes
[x] No
```
> Add missing data types

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
Removed unused fields
```
[ ] Yes
[X] No
```
> removed unused fields

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-1985
Ret 1985: Added fields for ET3 Respondent Name and Address
```
[ ] Yes
[x] No
```
> Ret 1985: Added fields for ET3 Respondent Name and Address

- build.gradle
Bump Version to 1.0.22
```
[ ] Yes
[x] No
```
> Bump Version 1.0.22

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-2001
Added transfer application data
```
[ ] Yes
[x] No
```
> RET-2001: added additional data for the transfer application page

- build.gradle
https://tools.hmcts.net/jira/browse/RET-2025
Bumped the version number to enable publish of new version
```
[ ] Yes
[  x ] No
```
> bumped up version number

- build.gradle
Bunp to 1.0.30
```
[ ] Yes
[x] No
```
> bunped version to 1.0.30

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-1845
Add suggest hearing venue page.
```
[ ] Yes
[x] No
```
> RET-1845. Suggest hearing venue.

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/Et3VettingType.java
Removed some fields on et3VettingType that were for storing html content
```
[ ] Yes
[x] No
```
> Removed et3 html fields from Et3VettingType

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtInitialConsiderationRule27.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtInitialConsiderationRule28.java
https://tools.hmcts.net/jira/browse/RET-2025
https://tools.hmcts.net/jira/browse/RET-2027
https://tools.hmcts.net/jira/browse/RET-2029
https://tools.hmcts.net/jira/browse/RET-2037
https://tools.hmcts.net/jira/browse/RET-2045
Initial consideration Rule 26 pages
```
[ ] Yes
[x] No
```
> Initial Consideration Integration

- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
Added missing Initial Consideration fields
```
[ ] Yes
[ x ] No
```
> Added extra Initial consideration fields

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantHearingPreference.java
ClaimantHearingPreference model is modified.
https://tools.hmcts.net/jira/browse/RET-2117
```
[ ] Yes
[ X ] No
```
> ClaimantHearingPreference model modified

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
All fields for ET3 Response journey
```
[ ] Yes
[x] No
```
> Added fields for ET3 response form

- build.gradle
- config/checkstyle/checkstyle.xml
- src/main/java/uk/gov/hmcts/et/common/model/bulk/BulkData.java
- src/main/java/uk/gov/hmcts/et/common/model/bulk/types/DynamicValueType.java
- src/main/java/uk/gov/hmcts/et/common/model/bulk/types/MultipleType.java
- src/main/java/uk/gov/hmcts/et/common/model/bulk/types/SearchType.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/Address.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/Et1CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtIcudlHearing.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/PaginatedSearchMetadata.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantHearingPreference.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantIndType.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondentSumType.java
- src/main/java/uk/gov/hmcts/et/common/model/generic/GenericCallbackResponse.java
- src/main/java/uk/gov/hmcts/et/common/model/listing/types/AdhocReportType.java
- src/main/java/uk/gov/hmcts/et/common/model/listing/types/ClaimServedType.java
- src/main/java/uk/gov/hmcts/et/common/model/multiples/MultipleConstants.java
- src/test/java/uk/gov/hmcts/et/common/model/ccd/CaseDataTest.java
- src/test/java/uk/gov/hmcts/et/common/model/listing/items/BFDateTypeItemComparatorTest.java
https://tools.hmcts.net/jira/browse/RET-1861
Check styles added
Names changed of variables used in other repos which is a breaking change
```
[X] Yes
[] No
```
> RET-1861- checkstyles added

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/bulk/types/DynamicFixedListType.java
- src/test/java/uk/gov/hmcts/et/common/model/bulk/types/DynamicFixedListTypeTest.java
Code changes required for RET-2155 so that select lists display a list element that is from the existing casedata in addition to items supplied in fixed list. Unit tests modified. 
https://tools.hmcts.net/jira/browse/RET-2155
```
[ ] Yes
[ X ] No
```
> Code changes required for RET-2155

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtInitialConsiderationRule27.java
https://tools.hmcts.net/jira/browse/RET-2214
added etICRule27NoJurisdictionReason
```
[ ] Yes
[x] No
```
> added etICRule27NoJurisdictionReason

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/generic/GenericCallbackResponse.java
Revert generic changes made
```
[ ] Yes
[X] No
```
> Reverted Generic Changes

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-2183
```
[ ] Yes
[x ] No
```
> RET-2183: Create and send a new Referral

- build.gradle
(https://tools.hmcts.net/jira/browse/RET-2183)
```
[ ] Yes
[x ] No
```
> Bump version to 49

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/NewEmploymentType.java
https://tools.hmcts.net/jira/browse/RET-1934
Add missing fields for new employment type
```
[ ] Yes
[x] No
> Add missing employment types

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/ReferralTypeItem.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ReferralType.java
RET-2183
Added Referral collection
```
[ ] Yes
[x] No
```
> Ret 2183 add new referral collection

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/Organisation.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RepresentedTypeR.java
https://tools.hmcts.net/jira/browse/RET-2197
Added Organisation for respondent rep
```
[ ] Yes
[X] No
```
> Add Organisation to respondent rep

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/Et3VettingType.java
https://tools.hmcts.net/jira/browse/RET-2201
Added fields to store PDFs
```
[ ] Yes
[X] No
```
> RET-2201 - Pdf store

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ReferralType.java
RET-2183/RET-2192 related fixes
Fixing some definitions that were named wrong
```
[ ] Yes
[x] No
```
> Updated version and refactored referer email -> referrent email

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/Organisation.java
> Legal Rep Fix

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RepresentedTypeR.java
https://tools.hmcts.net/jira/browse/RET-2197
Added missing yes or no field
```
[ ] Yes
[X] No
```
> Legal rep missing yesNo field

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/Et1CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/citizenhub/HubLink.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/citizenhub/HubLinks.java
https://tools.hmcts.net/jira/browse/RET-2260
Track citizen hub links and their statuses.
```
[ ] Yes
[x] No
```
> RET-2260. Add HubLinks to ET1CaseData.

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/Et1CaseData.java
https://tools.hmcts.net/jira/browse/RET-1935
Adding to claimantWorkAddressQuestion to Et1 model
```
[ ] Yes
[x] No
```
> Add claimantWorkAddressQuestion to ET1 case data model

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/Et1CaseData.java
[RET-2170](https://tools.hmcts.net/jira/browse/RET-2170)
Add ClaimantPcqId
```
[ ] Yes
[ x] No
```
> Add ClaimantPcqId

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/citizenhub/HubLinksStatuses.java
> RET-2227: Added alert statuses link

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/citizenhub/HubLinksStatuses.java
> Ret 2227 2

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/Et1CaseData.java
Move receiptDate to Et1CaseData so it can be used by ET1 form
```
[ ] Yes
[x] No
```
> Move receiptDate to Et1CaseData

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantRequestType.java
https://tools.hmcts.net/jira/browse/RET-2578
Bug fixes from final checks testing
Invalid date error message not displaying
Show ethosCaseReference for submitted claims
```
[ ] Yes
[x ] No
```
> RET-2578 Add 'otherClaim'

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/Et1CaseData.java
https://tools.hmcts.net/jira/browse/RET-1968
```
[ ] Yes
[ x] No
```
> Add typesOfClaim

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-2612
Added a field to track if the case rejected email has been sent
```
[ ] Yes
[x] No
```
> added field for case rejected email sent

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/CostsType.java
https://tools.hmcts.net/jira/browse/RET-2593
RET-2593: Added Pro Bono fields
```
[ ] Yes
[x] No
```
> RET-2593: Added Pro Bono fields

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-2590
Added suggestedHearingVenues
```
[ ] Yes
[x] No
```
> RET-2590: Added suggestedHearingVenues

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantType.java
https://tools.hmcts.net/jira/browse/RET-2818
Add hearing language preference field.
```
[ ] Yes
[x] No
```
> RET-2818. Add claimantHearingLanguage.

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantHearingPreference.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantType.java
https://tools.hmcts.net/jira/browse/RET-2868
Add contact + hearing language to hearing preferences
Remove properties from ClaimantType
```
[x] Yes
[ ] No
```
> RET-2868 - Add contact + hearing language to hearing preferences

- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/NoticeOfChangeAnswers.java
https://tools.hmcts.net/jira/browse/RET-2994
```
[ ] Yes
[x ] No
```
> RET-2994 added client name fields

- build.gradle
> build version incremented

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseUserAssignment.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseUserAssignmentData.java
https://tools.hmcts.net/jira/browse/RET-2843
Added structures to store case assignment data
```
[ ] Yes
[ x ] No
```
> RET-2843: Added structures to store case assignment data

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-3026
https://tools.hmcts.net/jira/browse/RET-2867
```
[ ] Yes
[x] No
```
> RET-3026 Select application to view

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-3116
https://tools.hmcts.net/jira/browse/RET-3117
```
[ ] Yes
[X] No
```
> Ret 3116 3117

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-2953
```
[ ] Yes
[ x] No
```
> RET-2953 added selectNotificationCollection

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-3048
RET-3048: Added view notifications field
```
[ ] Yes
[x] No
```
> RET-3048: Added view notifications field

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-2274
```
[ ] Yes
[ X] No
```
> One new field added

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-2896
```
[ ] Yes
[x] No
```
> Ret 2896 v2

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-2954
```
[ ] Yes
[x ] No
```
> RET-2954 added notification markdown

- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantIndType.java
- src/test/java/uk/gov/hmcts/et/common/model/ccd/CaseDataTest.java
https://tools.hmcts.net/jira/browse/RET-3341
-----
Updated claimantFullName method in ClaimantIndType to check if any data exists for claimantPreferredTitle.
-----
```
[ ] Yes
[X] No
```
> RET-3341 Staff cause list not displaying Claimant's title

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/DynamicListTypeItem.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/DynamicListType.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondentSumType.java
https://tools.hmcts.net/jira/browse/RET-3337
https://tools.hmcts.net/jira/browse/RET-3342
Added option to select which respondent on ET3 Form and save data per respondent
```
[ ] Yes
[X] No
```
> ET3 Changes

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/GenericTypeItem.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondNotificationType.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/SendNotificationType.java
https://tools.hmcts.net/jira/browse/RET-2956
```
[ ] Yes
[x] No
```
> Ret 2956 Provide something Tribunal asked for - Respond to a notification (ECM) - notify selected parties (email)

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/SendNotificationType.java
https://tools.hmcts.net/jira/browse/RET-2956
```
[ ] Yes
[ x] No
```
> RET-2956 added filed to sendNotificationType

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/SendNotificationType.java
https://tools.hmcts.net/jira/browse/RET-2956
```
[ ] Yes
[ x] No
```
> RET-2956 add fileds to sendNotification

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/SendNotificationType.java
https://tools.hmcts.net/jira/browse/RET-2927
Added 'notificationState' field to 'SendNotificationType'
```
[ ] Yes
[x ] No
```
> RET-2927: Add notificationState field

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/SendNotificationType.java
https://tools.hmcts.net/jira/browse/RET-2948
Added notifications tab
```
[] Yes
[x] No
```
> RET-2948: Added notifications tab

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantIndType.java
- src/test/java/uk/gov/hmcts/et/common/model/ccd/CaseDataTest.java
Method for formatting claimant "Title" is refactored.  Unit tests updated as well.
Locally tested with unit test only. To be tested on perftest with Docmosis.  
https://tools.hmcts.net/jira/browse/RET-3372
```
[ ] Yes
[X] No
```
> RET-3372 implementation

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/DocumentTypeItem.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/GenericTypeItem.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/DocumentType.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/UploadedDocumentType.java
https://tools.hmcts.net/jira/browse/RET-3344
Added builders to document related types
```
[] Yes
[x] No
```
> RET-3344: Added builders to document related types

- build.gradle
> Align tag and version

- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RepresentedTypeR.java
> Clarify what respRepName represents.

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/RetrieveOrgByIdResponse.java
> RET-3438: Added retrieve org by id response object

- .github/workflows/gradle.yml
- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-3108
Added bundlesRespondentUploadFile field
```
[] Yes
[x] No
```
> RET-3108: Added bundlesRespondentUploadFile field

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/TseAdminRecordDecisionType.java
https://tools.hmcts.net/jira/browse/RET-3233
Adding decision state to admin decision
```
[ ] Yes
[X] No
```
> Added tse admin decision state

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondentSumType.java
https://tools.hmcts.net/jira/browse/RET-3487
Added new fields to allow ET3 Save and Return
```
[ ] Yes
[X] No
```
> RET-3487: ET3 Save and Return

- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/GenericTseApplicationType.java
> RET-3794: Update to relocate respondent/claimant respond required field

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
> RET-2794: new responding to Tribunal text field

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/ListTypeItem.java
- src/test/java/uk/gov/hmcts/et/common/model/ccd/types/ListTypeItemTest.java
https://tools.hmcts.net/jira/browse/RET-3767
Added autoListFlag caseAdditionalSecurityFlag caseRestrictedFlag and caseInterpreterRequiredFlag
```
[] Yes
[x] No
```
> RET-3767: Added autoListFlag caseAdditionalSecurityFlag caseRestrictedFlag and caseInterpreterRequiredFlag

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/TseRespondType.java
https://tools.hmcts.net/jira/browse/RET-3792
Add property to track viewing of response
```
[ ] Yes
[x] No
```
> RET-3792 - Add property to track viewing of response

- .github/workflows/gradle.yml
- README.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Gradle update

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/UpdateReferralTypeItem.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ReferralType.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/UpdateReferralType.java
https://tools.hmcts.net/jira/browse/RET-3787
```
[ ] Yes
[X] No
```
> Ret 3787 latest2

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/CaseLink.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/LinkReason.java
https://tools.hmcts.net/confluence/display/RCCD/CCD+Supported+Field+Types#CCDSupportedFieldTypes-ccdTypeCaseLink
<html>
<body>
<p style="margin: 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(250, 250, 210); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: …
> RET-3602 - Add case linking to data model

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/bulk/types/DynamicFixedListType.java
- src/test/java/uk/gov/hmcts/et/common/model/bulk/types/DynamicFixedListTypeTest.java
https://tools.hmcts.net/jira/browse/RET-3773
Added DynamicFixedListType.from(label, code) for convenience
```
[] Yes
[x] No
```
> RET-3773: Added DynamicFixedListType.from(label, code) for convenience

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/hmc/CaseDetails.java
- src/test/java/uk/gov/hmcts/et/common/model/hmc/validator/BeanValidatorTest.java
https://tools.hmcts.net/jira/browse/RET-4044
Rename caseNameHmctsInternal
```
[x] Yes
[ ] No
```
> Ret 4044 - Rename caseNameHmctsInternal

- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-3514
Added isSystemUser attribute to CaseData model
```
[ ] Yes
[X] No
```
> RET-3514 Added systemUserYesOrNo attribute to CaseData model

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-4019
```
[ ] Yes
[x] No
```
> RET-4019 Hearing unavailability dates

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondNotificationType.java
https://tools.hmcts.net/jira/browse/RET-4021
Added state and isClaimantResponseDue for tribunal responses to notifications
```
[] Yes
[x] No
```
> RET-4021: Added state and isClaimantResponseDue for tribunal responses to notifications

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/Document.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/UploadedDocumentType.java
https://tools.hmcts.net/jira/browse/RET-4176
Add categoryId to Document
```
[ ] Yes
[x] No
```
> RET- - 4176 - Add categoryId to Document

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/PseResponseType.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/TseRespondType.java
https://tools.hmcts.net/jira/browse/RET-4062
CUI side of the Rule 92 for non system user
Add StoredPending in TseRespondType
> RET-4062 - TseRespondType

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/citizenhub/ClaimantTse.java
https://tools.hmcts.net/jira/browse/RET-4104
Adding Welsh email content.
> RET-4104 - Welsh- Notifications emails for case progression

- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-4236
Transferred case link field is added.
> Transferred case field added

- build.gradle
https://tools.hmcts.net/jira/browse/RET-4236
gradle version increment
> version increment

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtICFurtherInfoAnswers.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtICHearingListedAnswers.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtICListForFinalHearing.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtICListForPreliminaryHearing.java
https://tools.hmcts.net/jira/browse/RET-4192
> RET-4192 - Initial Consideration

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/ListTypeItem.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/RepresentedTypeRItem.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RepresentedTypeC.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RepresentedTypeR.java
- src/test/java/uk/gov/hmcts/et/common/model/ccd/CaseDataTest.java
- src/test/java/uk/gov/hmcts/et/common/model/ccd/types/ListTypeItemTest.java
https://tools.hmcts.net/jira/browse/RET-4374
Added organisationId and nonMyHmctsOrganisationId
```
[] Yes
[x] No
```
> RET-4374: Added organisationId and nonMyHmctsOrganisationId

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/HearingBundleType.java
https://tools.hmcts.net/jira/browse/RET-4400
Add some additional values to HearingBundleType
> RET-4400 bundles tab

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
> added waRule21ReferralSent

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/FlagDetailType.java
> Added CaseFlag fields

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/multiples/MultipleData.java
https://tools.hmcts.net/jira/browse/RET-4687
Add leadCaseId
> RET-4687 - Add leadCaseId

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/multiples/MultipleData.java
https://tools.hmcts.net/jira/browse/RET-4250
Add Case Stayed on batch update
```
[] Yes
[x] No
```
> RET-4250: Add Case Stayed on batch update

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-4281
new field added
> new field added

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-4281
> field name corrected

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/generic/GenericCCDRequest.java
- src/main/java/uk/gov/hmcts/et/common/model/multiples/MultipleData.java
https://tools.hmcts.net/jira/browse/RET-4705
Added referral types for Multiples
```
[] Yes
[x] No
```
> RET-4705: Added referral types for Multiples

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/DocumentType.java
https://tools.hmcts.net/jira/browse/RET-4874
added field documentIndex to DocumentType
> added field documentIndex to DocumentType

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/multiples/MultipleData.java
https://tools.hmcts.net/jira/browse/RET-4711
Add send notification to all
> RET-4711 - Add send notification to all

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/SendNotificationType.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/SendNotificationTypeMultiple.java
https://tools.hmcts.net/jira/browse/RET-4711
Create SendNotificationTypeMultiple
> RET-4711 - Create SendNotificationTypeMultiple

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/SendNotificationType.java
https://tools.hmcts.net/jira/browse/RET-4743
Add notification from multiple
> RET-4743 - Add notification from multiple

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondentSumType.java
https://tools.hmcts.net/jira/browse/RET-4926
ResponseReceivedCounter for WA
> RET-4926: ResponseReceivedCounter for WA

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/SendNotificationTypeMultiple.java
- src/main/java/uk/gov/hmcts/et/common/model/multiples/MultipleData.java
https://tools.hmcts.net/jira/browse/RET-4715
Add property for batch update notifications
> RET-4715 - Add property for batch update notifications

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/NotificationExtract.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/NotificationsExtract.java
- src/main/java/uk/gov/hmcts/et/common/model/multiples/MultipleData.java
https://tools.hmcts.net/jira/browse/RET-4732
Add notification extract to multiple
> RET-4732 - Add notification extract to multiple

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/PseResponseType.java
https://tools.hmcts.net/jira/browse/RET-5010
Add WA Enablers for Claimant Response to ECC
> RET-5010: Claimant Response to ECC

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/CaseNote.java
- src/main/java/uk/gov/hmcts/et/common/model/multiples/MultipleData.java
https://tools.hmcts.net/jira/browse/RET-5053
Add case note feature
> RET-5053 - Add case note feature

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/RemovedHearingBundleItem.java
https://tools.hmcts.net/jira/browse/RET-4774
introduce new fields to facilitate removing hearing bundles
> RemovedHearingBundleItem impl

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/bundle/MultipleBundleCreateRequest.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/generic/BaseCaseData.java
https://tools.hmcts.net/jira/browse/RET-5064
Add DCF on multiple
> RET-5064 - Add DCF on multiple

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/generic/BaseCaseData.java
https://tools.hmcts.net/jira/browse/RET-4762
nextListedDate on a Multiples type
```
[] Yes
[x] No
```
> RET-4762: nextListedDate on a Multiples type

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/multiples/MultipleData.java
https://tools.hmcts.net/jira/browse/RET-5202
Add multiple note
> RET-5202 - Add multiple note

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/GenericTypeItem.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/items/ListTypeItem.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/OrganisationUsersIdamUser.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/OrganisationUsersResponse.java
- src/test/java/uk/gov/hmcts/et/common/model/ccd/types/ListTypeItemTest.java
https://tools.hmcts.net/jira/browse/RET-5201
Added OrganisationUsersResponse models
```
[] Yes
[x] No
```
> RET-5201: Added OrganisationUsersResponse models

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/PseResponseType.java
https://tools.hmcts.net/jira/browse/RET-5206
Add author to response
> RET-5206 - Add author to response

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/multiples/MultipleData.java
https://tools.hmcts.net/jira/browse/RET-5205
Second CaseIdCollection as AmendMultipleDetails is already using the other one.
> RET-5205: Alternative CaseIdCollection

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/multiples/MultipleData.java
https://tools.hmcts.net/jira/browse/RET-5232
Added jurisdictions list
```
[] Yes
[x] No
```
> RET-5232: Added jurisdictions list

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/multiples/MultipleConstants.java
https://tools.hmcts.net/jira/browse/RET-5209
Add claimant header
> RET-5209 - Add claimant header

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/multiples/MultipleData.java
https://tools.hmcts.net/jira/browse/RET-5266
Update live cases only
> RET-5266 - Update live cases only

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/DraftAndSignJudgement.java
> Draft And Sign Judgement

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtIcudlHearing.java
https://tools.hmcts.net/jira/browse/RET-5249
Code refactored to rename fields as per the requirements of ret-5249
> fields refactored for ret-5249 required changes

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondentSumType.java
No jira link
removed the field et3ContactPreferencePostReason
> ET3Updates

- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
>  Initial Consideration Document Collections

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondentSumType.java
respondent hearing panel preference fields added
https://tools.hmcts.net/jira/browse/RET-5437
hearing panel preference fields added for respondent
- [x ] commit messages are meaningful and follow good commit message guidelines
> hearing panel preference fields added

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-5437
Hearing panel preference related fields added for the IC event
> two new fields added

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondentSumType.java
https://tools.hmcts.net/jira/browse/RET-5437
token change to fix lib tag issue
> token change to fix lib tag issue

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/ClaimantHearingPreference.java
[See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
](https://tools.hmcts.net/jira/browse/RET-5436)
> hearing panel preference fields

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtICListForFinalHearingUpdated.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtICListForPreliminaryHearingUpdated.java
> updated field names to replace the hidden list

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtICListForFinalHearingUpdated.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtICListForPreliminaryHearingUpdated.java
> updated property names

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtICHearingListedAnswers.java
https://tools.hmcts.net/jira/browse/RET-5443
New fields required for ret-5443 added
> new fields added

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondentSumType.java
There is no Jira Link
Added ET3FormWelsh field to RespondentSumType
> Added ET3FormWelsh field to RespondentSumType

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/EtICListForFinalHearingUpdated.java
https://tools.hmcts.net/jira/browse/RET-5500
- added new fields to support hearing type orders
> add new fields for hearing orders

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
https://tools.hmcts.net/jira/browse/RET-2853
Added a ttl retrospective date for migration. The value is used to set full TTL details in the callbacks side by capturing the update in case history.
> ttl migration data field

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondentTse.java
- Added new class Respondent Tse
> create Respondent Tse data

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/RespondentTse.java
> Res Tse Api

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/TTL.java
https://tools.hmcts.net/jira/browse/RET-2853
TTL fields data type corrected from String to LocalDate
> field data type correction

- build.gradle
- src/main/java/uk/gov/hmcts/et/common/model/ccd/CaseData.java
- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/DigitalCaseFileType.java
> DCF Updates

- src/main/java/uk/gov/hmcts/et/common/model/ccd/types/BFActionType.java
https://tools.hmcts.net/jira/browse/RET-5275
a wa task creation tracker field is added
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
- [x ] commit messages are meaningful and follow good commit message guidelines
> field added

- .github/workflows/ado_artifacts_build.yml
Update ADO logic to include renovate builds and comment the published version in the PR to make it easier for devs to see
> Update ADO logic
